name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * 6'
defaults:
  run:
    shell: bash
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    runs-on: ${{matrix.os}}
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python}}
      - name: Install Hatch
        run: |
          pip install hatch
      - name: Install dependencies
        run: |
          hatch run test:pip freeze
      - name: Run tests
        run: |
          hatch run test:test
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Hatch
        run: |
          pip install hatch
      - name: Install dependencies
        run: |
          hatch run style:pip freeze
          hatch run types:pip freeze
      - name: Check style
        if: always()
        run: |
          hatch run style:check
      - name: Check types
        if: always()
        run: |
          hatch run types:check
